apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argo
spec:
  project: default
  source:
    repoURL: "https://traefik.github.io/charts"
    chart: "traefik"
    targetRevision: "v34.2.0"   # Could use latest here for CD
    helm:
      releaseName: "traefik"
      values: |
        service:
          type: LoadBalancer
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: nlb
            service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
