# ingresses/ingresses-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-routes
  namespace: argo 
spec:
  project: default
  source:
    repoURL: "https://github.com/MarjanJordanovski/swissborg.git"
    targetRevision: "main"
    path: "ingresses"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
