# storage/storage-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-storage
  namespace: argo
spec:
  project: default
  source:
    repoURL: "https://github.com/MarjanJordanovski/swissborg.git"
    targetRevision: "main"
    path: "storage"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: identity 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
