apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
  namespace: identity
data:
  argorealm.json: |
    {
      "id": "argorealm",
      "realm": "argorealm",
      "enabled": true,
      "users": [
        {
          "username": "swissborg",
          "enabled": true,
          "emailVerified": true,
          "firstName": "swissborg",
          "lastName": "swissborg",
          "credentials": [
            {
              "type": "password",
              "value": "swissborg2025"
            }
          ]
        }
      ],
      "clients": [
        {
          "clientId": "argocd",
          "publicClient": true,
          "redirectUris": ["https://EXTERNAL_IP/argocd/auth/callback"],
          "defaultRoles": []
        }
      ]
    }
